### ISSUE TITLE
Add Umlauts to the Right Side of German Keyboard Keys

### ISSUE THREAD

**Issue by dean-futo** [futo-org/futo-keyboard-layouts#106]
A user requests the ability to add umlauts to the right side of regular keys on the German keyboard, similar to how it's done on other keyboards.
![1000013362](https://github.com/user-attachments/assets/52c26130-c9fb-41dc-849a-f55271e68291)
![1000013364](https://github.com/user-attachments/assets/630edc0c-869a-4e65-b78a-7a6f4a16854b)

Email ticket #8453

**Comment by tenextractor** [comment]
Don't we already have this layout?
![image](https://github.com/user-attachments/assets/a3ff3acb-ef51-49fb-ba09-6d739f07a05f)

**Comment by abb128** [comment]
This is already the default option when adding German
