### ISSUE TITLE
Add Amazigh Layout in Both Tifinagh and Latin Scripts

### ISSUE THREAD

**Issue by abdelhaqueidali** [futo-org/futo-keyboard-layouts#11]
### Language

Amazigh

### Description

Amazigh has two scripts, Tifinagh, its original one and latin.

For Tifinagh :
```
ⴰⵣⴻⵔⵜⵢⵓⵉⵄⵃ
ⵇⵙⴷⴼⴳⵀⵊⴽⵍⵎ
ⵡⵅⵛⵖⴱⵏⵯ
```
Long press the previous key => result
ⵣ => ⵥ
ⴻ => ⵦ
ⵔ => ⵕ
ⵜ => ⵟ/ⵝ
ⵓ => ⵧ
ⵇ => ⵈ
ⵙ => ⵚ
ⴷ => ⴹ/ⴸ/ⴺ
ⴼ => ⵠ
ⴳ => ⴴ/ⴵ/ⴶ
ⵀ => ⵂ/ⵁ
ⵊ => ⵌ/ⵋ
ⴽ => ⴾ/ⴿ
ⵍ => ⵰
ⵎ => ⵿
ⵡ => ⵯ
ⵅ => ⵆ
ⵛ => ⵞ
ⵖ => ⵗ
ⴱ => ⵒ/ⴲ
ⵏ => ⵐ/ⵑ

Latin :
```
Azertyuiɛḥ
qsdfghjklm
wxcɣbnʷ
```
 z => ẓ
r => ṛ
t => ṭ
u => o
s => ṣ
d => ḍ
f => v
g => ǧ
h => ḥ
w => ʷ
c => č
ɣ => γ
b => p
ʷ => ° 

The language code for Amazigh (Tifinagh) is ber or zgh, we prefer zgh since it is the one supported on android devices for Amazigh in Tifinagh.
For latin we can just make it seperated from the previous one since people still use it along side Tifinagh, so they need to be able to set those two scripts to be used. Latin uses the code ber-Latn. But supported on android devices as Amazigh (Kabyle) under the code kab

The name of each version and the name:
Amazigh Languge = zgh (this for Tifinagh)
Amazigh (Kabyle) Language = kab (This for latin)
For dictionary, Tifinagh one is available here, the repository is meant for layouts of MOK for Amazigh:
https://github.com/abdelhaqueidali/Layouts-for-Multiling-O-Keyboard

### Complexity

not complex, one character for each sound in the language.

**Comment by tenextractor** [comment]
What do you think about this layout?
```
č ẓ ɛ ṛ ṭ ɣ ǧ ḥ ř ṣ
a z e r t y u i o p
q s d f g h j k l m
w x c v b n ʷ ḍ
```
This would give easy access to the letters Ẓ, Ṛ, Ṭ, O, Ṣ, V, Ḍ, Ǧ, Ḥ, ʷ, Č, Y, P instead of having to hold down keys for them.
It also makes typing URLs or any ASCII data easier, without having to switch back to an English layout.

**Comment by abdelhaqueidali** [comment]
> What do you think about this layout?
> 
> ```
> č ẓ ɛ ṛ ṭ ɣ ǧ ḥ ř ṣ
> a z e r t y u i o p
> q s d f g h j k l m
> w x c v b n ʷ ḍ
> ```
> 
> This would give easy access to the letters Ẓ, Ṛ, Ṭ, O, Ṣ, V, Ḍ, Ǧ, Ḥ, ʷ, Č, Y, P instead of having to hold down keys for them. It also makes typing URLs or any ASCII data easier, without having to switch back to an English layout.


Too much letters on the screen is not good.
Try SwiftKey on your phone, For Amazigh (Tifinagh) look for Tamazigh. For Amazigh (Latin) look for Taqbaylit.
See how the standard way of arranging letters.
Most people, I can say 80 to 90% are familiar with those design since it is the standard way, for phones and computers. Gboard has recently added a new design and people are struggling with it, so we always ask them to change it, and this new design I am talking about tried the same thing, putting all the letters on the screen at once, for both Tifinagh and Latin.

**Comment by abdelhaqueidali** [comment]
Here are the layouts.
Amazigh code is zgh
Amazigh latin one is zgh-latn

1 - AMAZIGH SCRIPT LAYOUTS

LAYOUT 1 (Priority)
Amazigh/amazigh.yaml
name: Amazigh
languages: zgh
rows:
  - letters: # rowkeys_amazigh1.xml
    - ['ⴰ']
    - ['ⵣ', 'ⵥ']
    - ['ⴻ']
    - ['ⵔ', 'ⵕ']
    - ['ⵜ', 'ⵟ']
    - ['ⵢ']
    - ['ⵓ']
    - ['ⵉ']
    - ['ⵄ']
    - ['ⵃ']
  - letters: # rowkeys_amazigh2.xml
    - ['ⵇ']
    - ['ⵙ', 'ⵚ']
    - ['ⴷ', 'ⴹ']
    - ['ⴼ', 'ⵠ']
    - ['ⴳ', 'ⴳⵯ']
    - ['ⵀ']
    - ['ⵊ']
    - ['ⴽ']
    - ['ⵍ']
    - ['ⵎ']
  - letters: # rowkeys_amazigh3.xml
    - ['ⵡ']
    - ['ⵅ']
    - ['ⵛ']
    - ['ⵖ']
    - ['ⴱ', 'ⵒ']
    - ['ⵏ']
    - ['ⵯ']

LAYOUT 2
Amazigh/amazigh_extended.yaml
name: Amazigh (Extended)
languages: zgh
rows:
  - letters: # rowkeys_amazigh1.xml
    - ['ⴰ']
    - ['ⵣ', 'ⵥ', 'ⵤ']
    - ['ⴻ', 'ⵦ']
    - ['ⵔ', 'ⵕ']
    - ['ⵜ', 'ⵟ', 'ⵝ']
    - ['ⵢ']
    - ['ⵓ', 'ⵧ']
    - ['ⵉ']
    - ['ⵄ']
    - ['ⵃ']
  - letters: # rowkeys_amazigh2.xml
    - ['ⵇ', 'ⵈ']
    - ['ⵙ', 'ⵚ']
    - ['ⴷ', 'ⴹ', 'ⴸ', 'ⴺ']
    - ['ⴼ', 'ⵠ']
    - ['ⴳ', 'ⴴ', 'ⴵ', 'ⴶ']
    - ['ⵀ', 'ⵂ', 'ⵁ']
    - ['ⵊ', 'ⵋ', 'ⵌ']
    - ['ⴽ', 'ⴾ', 'ⴿ']
    - ['ⵍ', '⵰']
    - ['ⵎ', '⵿']
  - letters: # rowkeys_amazigh3.xml
    - ['ⵡ']
    - ['ⵅ', 'ⵆ']
    - ['ⵛ', 'ⵞ']
    - ['ⵖ', 'ⵗ']
    - ['ⴱ', 'ⵒ', 'ⴲ']
    - ['ⵏ', 'ⵐ', 'ⵑ']
    - ['ⵯ', 'ⴳⵯ', 'ⴽⵯ']

LAYOUT 3
Amazigh/amazigh_mini.yaml
name: Mini
languages: zgh
rows:
  - letters: # rowkeys_amazigh1.xml
    - ['ⴷ', 'ⵇ']
    - ['ⵔ', 'ⵛ']
    - ['ⵎ', 'ⴽ']
    - ['ⵍ', 'ⵊ']
    - ['ⵢ', 'ⵟ']
    - ['ⵖ', 'ⵡ']
  - letters: # rowkeys_amazigh2.xml
    - ['ⴰ', 'ⵕ']
    - ['ⵜ', 'ⵯ']
    - ['ⵉ', 'ⴻ']
    - ['ⵏ', 'ⴹ']
    - ['ⵙ', 'ⵄ']
    - ['ⵓ', 'ⵚ']
  - letters: # rowkeys_amazigh3.xml
    - ['ⴱ', 'ⵀ']
    - ['ⴼ', 'ⵃ']
    - ['ⵣ', 'ⵥ']
    - ['ⴳ', 'ⵅ']

2 - AMAZIGH LATIN SCRIPT :

1 - AZERTY LAYOUT :
Amazigh (Latin)/amazigh_azerty.yaml

name: Amazigh (Basic)
languages: zgh-Latn
rows:
  - letters: # rowkeys_amazigh1.xml
    - ['a']
    - ['z', 'ẓ']
    - ['e']
    - ['r', 'ṛ']
    - ['t', 'ṭ']
    - ['y']
    - ['u', 'o']
    - ['i']
    - ['ɛ']
    - ['ḥ']
  - letters: # rowkeys_amazigh2.xml
    - ['q']
    - ['s', 'ṣ']
    - ['d', 'ḍ']
    - ['f', 'v']
    - ['g', 'ǧ']
    - ['h', 'ḥ']
    - ['j']
    - ['k']
    - ['l']
    - ['m']
  - letters: # rowkeys_amazigh3.xml
    - ['w']
    - ['x']
    - ['c', 'č']
    - ['ɣ', 'γ']
    - ['b', 'p']
    - ['n']
    - ['ʷ', '°']
    - ['‐']
