### ISSUE TITLE
Old Style Keyboard Layout for Special Letters

### ISSUE THREAD

**Issue by AndrejusAnto** [futo-org/futo-keyboard-layouts#49]
Is it possible to add/include old style layout for foreign language (Lithuania) that include special letters on main keyboard layout like? ![unnamed-small-small](https://github.com/futo-org/futo-keyboard-layouts/assets/23524922/a00384e6-a0f4-499d-a5da-a4a75c7bf2d8)

**Comment by tenextractor** [comment]
Added in #82
