### ISSUE TITLE
Numbers Misaligned on Number-Only Keyboard

### ISSUE THREAD

**Issue by Vrishabh-D-B** [futo-org/futo-keyboard-layouts#73]
### What happened?

![Screenshot_20240821_160104](https://github.com/user-attachments/assets/295473a3-91ba-40a2-a748-d26e5baaf956)

As you can see in the screenshot, numbers are a bit to left. This does not happen always but only sometimes.

### Keyboard Version

0.1.23.2

**Comment by dean-futo** [comment]
@Vrishabh-D-B this will be fixed in the next release. For now, feel free to use our latest nightly build, where it is already fixed:  https://keyboard.futo.org/nightly-apk
