### ISSUE TITLE
Comma-Question Mark Symbol Incorrectly Pops Up in Spanish Layout

### ISSUE THREAD

**Issue by dean-futo** [futo-org/futo-keyboard-layouts#78]
### What happened?

When a spanish-speaking user long-presses the period symbol _._ and chooses the question mark symbol _?_, a comma-question mark symbol _,?_ incorrectly pops up.
![Screenshot_2024-10-30-14-11-18-397](https://github.com/user-attachments/assets/462937c5-fe23-426d-a357-cec7b563cfa0)

### Keyboard Version

Unspecified

**Comment by abb128** [comment]
Fixed in 0.1.24
